#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Role: base
cookbook 'apt'
cookbook 'build-essential'

cookbook 'git'
cookbook 'vim'
cookbook 'dotdeb',
	:git => "https://github.com/ffuenf/chef-dotdeb",
	:ref => "master"

# Role: web
cookbook 'python'
cookbook 'mysql'
cookbook 'php'
cookbook 'composer'

# Role: application
cookbook "grimoire",
	:git => "https://github.com/andygrunwald/chef-grimoire",
	:ref => "master"

cookbook "supervisor",
	:git => "https://github.com/poise/supervisor",
	:ref => "master"

cookbook 'rabbitmq'

cookbook "jacobine",
	:git => "https://github.com/andygrunwald/chef-jacobine.git",
	:ref => "master"

cookbook "linguist",
	:git => "https://github.com/andygrunwald/chef-github-linguist",
	:ref => "master"
