#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Role: base
cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'vim'

# Role: web
cookbook 'python'
cookbook 'mysql'
cookbook 'php'
cookbook 'composer'

# Role: application
cookbook "repositoryhandler",
	:git => "https://github.com/andygrunwald/chef-repositoryhandler",
	:ref => "master"

cookbook "cvsanaly",
	:git => "https://github.com/andygrunwald/chef-cvsanaly",
	:ref => "master"

cookbook "supervisor",
	:git => "https://github.com/poise/supervisor",
	:ref => "master"

cookbook 'rabbitmq'

cookbook "typo3analytics",
	:git => "https://github.com/andygrunwald/chef-typo3analytics",
	:ref => "master"

cookbook "github-linguist",
	:git => "https://github.com/andygrunwald/chef-github-linguist",
	:ref => "master"